Web_proyect/Web_proyect/urls.py
from django.contrib import admin
from django.urls import path, include
from web_app import views

from django.conf import settings # Importar la ruta del contenido multimedia
from django.conf.urls.static import static # Importe para usar metodos de los archivos estaticos para contenido multimedia

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #path('web_app/', include('web_app.urls')), #se ingresa con web_app/names
    path('', include('web_app.urls')), #se ingresa sin nombre de la app
    path('servicios/', include('web_app_servicios.urls')), #llama las urls de la aplicacion servicios
    path('blog/', include('blog.urls')), #llama las urls de la aplicacion blog
    path('contacto/', include('contacto.urls')), #llama las urls de la aplicacion contacto
    path('tienda/', include('tienda.urls')), # llama las urls de la app tienda
    path('carrito/', include('carrito.urls')), # llama las urls de la app carrito
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # Añadir la ruta del contenido multimedia.

Web_proyect/blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('', views.blog, name="blog"), # el parametro name es opcional
    path('categoria/<int:categoria_id>', views.categoria, name="categoria"), # parametro categoria_id de la tabla categorias llevarlo en la peticion
]

Web_proyect/carrito/urls.py
from django.urls import path
from carrito import views

app_name = 'carrito' #namespace para llamar este conjunto de urls. || app_name: nombre de variable reservado para asignar namespace.

urlpatterns = [
    #path('', views.carrito, name='carrito'),
    path('agregar/<int:producto_id>', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>', views.eliminar_producto , name='eliminar'),
    path('restar/<int:producto_id>', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carrito, name='limpiar'),
]

Web_proyect/tienda/urls.py
from django.urls import path
from tienda import views

urlpatterns = [
    path('', views.tienda, name='tienda'),
]

Web_proyect/tienda/models.py
from django.db import models

# Create your models here.
class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'CategoriaProd'
        verbose_name_plural = 'CategoriasProd'

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categoria = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to = 'tienda', null=True, blank = True)
    precio =models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.nombre

Web_proyect/tienda/views.py
from django.shortcuts import render
from .models import CategoriaProd, Producto

# Create your views here.
def tienda(request):

    productos = Producto.objects.all() # importando todo los productos guardados en la DDBB.
    return render(request, 'tienda.html', {'productos':productos})

Web_proyect/tienda/templates/tienda.html
{% extends 'base.html' %}

{% load static %}

{% block titlee %}tienda{% endblock %}

{% block content %}
<div class="container-sm">
    <div style="background-color: darkslategrey; text-align: center; float: right;" class="p-2 my-2 mx-1 mr-3 text-white">
        <!-- <p>Aca iria el carrito de compras</p> -->
        <!-- <p>Total: {{importe_total_carrito}}</p> -->
        {% include "widget_carrito.html" %}
    </div>
    <section class="row" style="margin: 20px auto;">
    {% for producto in productos %}
        <div class="col-md-4">
            <div class="card bg-light my-2 mx-1 w-100" style="height: 40rem; text-align: center;">
                <div class="card-header" style="text-transform: uppercase;"><b>Promoción</b></div>
                <img class="card-img-top" style="height: 20rem; width: 100%;" src="{{producto.imagen.url}}" alt="imagen producto">
                <div class="card-body">
                    <h4 class="card-title">{{producto.nombre}}</h4>
                    <p class="card-text">{{producto.precio|floatformat:'g'}} $</p> <!--|floatformat:0 es para mostrar la variable float con 0 decimales, |floatformat:'g' muestra separacion de miles-->
                    <a href="" class="btn btn-outline-primary">Detalles</a>
                </div>
                <div class="card-footer">
                    <a href="{% url 'carrito:agregar' producto.id %}" class="btn btn-success">Añadir al carrito</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </section>
</div>
 <!-- Seccion para seleccionar las categorias -->

{% endblock %}

Web_proyect/tienda/templates/tienda_base.html
{% extends 'base.html' %}

{% load static %}
{% block titlee %}tienda{% endblock %}
{% block content %}
{% for producto in productos %}
<section class="page-section clearfix">
    <div class="container">
      <div class="intro">

        {% if producto.imagen %}
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{producto.imagen.url}}" alt="" style="width: 50%;">

        {% else %}
        <!-- <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="https://odinstore.co/wp-content/uploads/2020/12/CamisetaMetallicaRockon.jpg" alt="" style="width: 50%;"> -->
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'web_app/img/CamisetaMetallicaRockon.jpg' %}" alt="" style="width: 50%;">

        {% endif %}

        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-lower">{{producto.nombre}}</span>
            <span class="section-heading-upper">Precio: {{producto.precio}}$</span>
          </h2>
          <div style="text-align: left; font-size: 0.8em;">
            <p><b>Disponibilidad:</b>  {{producto.disponibilidad}}</p>
            <p><b>Categoria:</b>  {{producto.categoria}}</p>           
          </div>
          
         
        </div>
      </div>
    </div>
  </section>
  <hr>


  {% endfor %}
 </section>

 <!-- Seccion para seleccionar las categorias -->
<section">
    <div style="width: 75%; background-color: rgb(85, 199, 134); color: white; text-align: center; margin: auto;">
        Categorias: 
        {% for producto in productos %}
            {% for categoria in producto.categoria.all.distinct %}
                <a href="{% url 'categoria' categoria.id %}" class="linksCategorias">{{categoria.nombre}}</a>
            {% endfor %} &nbsp;&nbsp;
        {% endfor %}
    </div>
</section>
{% endblock %}

Web_proyect/tienda/templates/widget_carrito.html
<table class="table table-bordered table-hover text-center text-white">
    <thead>
        <tr>
            <th colspan="3">Carrito de compras</th> 
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Valor</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carrito.items %}
            {% for key, value in request.session.carrito.items %}
                <tr>
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carrito:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carrito:restar' value.producto_id %}" class="btn btn-sm btn-danger">-</a><br>
                        {{value.precio|floatformat:'g'}} $<br>                                               
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3"><div class="alert alert-danger" >Sin productos</div></td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2">Total</td>
            <td>{{importe_total_carrito|floatformat:'g'}} $</td>
        </tr>
    </tfoot>
</table>